version: '3.8'

services:
  backend:
    build: ./server
    ports:
      - "8080:8080"
    env_file:
      - .env

  frontend:
    build: ./client
    ports:
      - "3000:3000"
    depends_on:
      - backend
